### ISSUE TITLE
Team image incorrect sized on wide screen

### ISSUE THREAD

**Issue by Axel8s** [BasketLummen/Website#58]
On a 4K screen the bottom half of the team picture is not visible.
![image](https://user-images.githubusercontent.com/33456537/32497589-56b79910-c3cd-11e7-955b-1a92661f0ab6.png)

**Comment by yvesgoeleven** [comment]
@Axel8s I can 'fix' this in 2 ways

* Remove some of the top of the image
* Increase the height of the image container, but this pushes the content down, with the potential that it becomes invisible and therefore not found by visitors

**Comment by Axel8s** [comment]
@yvesgoeleven What we do at our customers to prevent this is limit the max width of the screen to 1024 and show 2 margins on the left and the right:
![image](https://user-images.githubusercontent.com/33456537/32537829-4197e692-c464-11e7-946a-780d035686f5.png)

**Comment by yvesgoeleven** [comment]
@Axel8s that's an option as well (I personally like wide screen images though)

Maybe we can use some smarts to determine the height (and/or center) of the image using computer vision https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/

**Comment by Axel8s** [comment]
@yvesgoeleven I see it can recognize faces in one of the examples. So if computer vision can recognize faces and add some space above the highest face and below the lowest face it could work.

**Comment by yvesgoeleven** [comment]
@axel8s heb zowel de bovenkant van de image afgedaan alsook het frame groter gemaakt. het hoogte verschil tussen thijmen en de coach was te groot om het er met de afzonderlijke maatregelen tussen te laten passen.

**Comment by yvesgoeleven** [comment]
Het frame van de foto is nu hoger gemaakt
